export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LIST_RECEIVE_REQUEST = 'LIST_RECEIVE_REQUEST';
export const LIST_RECEIVE_SUCCESS = 'LIST_RECEIVE_SUCCESS';
export const LIST_RECEIVE_FAILURE = 'LIST_RECEIVE_FAILURE';

export const LIST_RECEIVEDETAILS_REQUEST = 'LIST_PARTNUMBER_REQUEST';
export const LIST_RECEIVEDETAILS_SUCCESS = 'LIST_PARTNUMBER_SUCCESS';
export const LIST_RECEIVEDETAILS_FAILURE = 'LIST_PARTNUMBER_FAILURE';

export const LIST_RACKINFOS_REQUEST = 'LIST_RACKINFOS_REQUEST';
export const LIST_RACKINFOS_SUCCESS = 'LIST_RACKINFOS_SUCCESS';
export const LIST_RACKINFOS_FAILURE = 'LIST_RACKINFOS_FAILURE';

export const LIST_RACKNAME_REQUEST = 'LIST_RACKNAME_REQUEST';
export const LIST_RACKNAME_SUCCESS = 'LIST_RACKNAME_SUCCESS';
export const LIST_RACKNAME_FAILURE = 'LIST_RACKNAME_FAILURE';

export const LIST_SCANDATA_REQUEST = 'LIST_SCANDATA_REQUEST';
export const LIST_SCANDATA_SUCCESS = 'LIST_SCANDATA_SUCCESS';
export const LIST_SCANDATA_FAILURE = 'LIST_SCANDATA_FAILURE';
