export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LIST_ISSUE_REQUEST = 'LIST_ISSUE_REQUEST';
export const LIST_ISSUE_SUCCESS = 'LIST_ISSUE_SUCCESS';
export const LIST_ISSUE_FAILURE = 'LIST_ISSUE_FAILURE';
