export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LIST_DELETEFORMDATA_REQUEST = 'LIST_DELETEFORMDATA_REQUEST';
export const LIST_DELETEFORMDATA_SUCCESS = 'LIST_DELETEFORMDATA_SUCCESS';
export const LIST_DELETEFORMDATA_FAILURE = 'LIST_DELETEFORMDATA_FAILURE';

export const LIST_DELETEITEMS_REQUEST = 'LIST_DELETEITEMS_REQUEST';
export const LIST_DELETEITEMS_SUCCESS = 'LIST_DELETEITEMS_SUCCESS';
export const LIST_DELETEITEMS_FAILURE = 'LIST_DELETEITEMS_FAILURE';
